export const TEXTS = {
    TITLE: "I'm Licheng Wang",
    BIO_1: "A Software Engineer",
    BIO_2: "focusing on Blockchain & Data Science",
    ABOUT_ME: "About Me",
    SKILLS: "Skills",
    EXPERIENCE: "Experience",
    MY_STORY: "My Story",
    MY_STORY_CONTENT: "I'm a Software Engineer with over 3 years of experience and a deep passion for blockchain, AI, and Machine Learning. I'm currently pursuing a graduate certificate in AI & ML at Conestoga College, where I focus on Data Analysis, Data Engineering, and advanced ML algorithms.",
    LINKEDIN_LINK: "https://www.linkedin.com/in/lichengwang/",
    GITHUB_LINK: "https://github.com/WangWang0226",
    MEDIUM_LINK: "https://medium.com/@eeha8834",
    TALK_TO_AI: "Chat with my AI agent (Coming Soon)",
    VIEW_RESUME: "View my Resume",
    BLOCKCHAIN_ENGINEER: "Blockchain Smart Contract Engineer",
    ANDROID_ENGINEER: "Android Engineer",
    PELITH_JOB_DESC: "Successfully developed and deployed decentralized applications (DEX, ICO, Airdrop, Dual-Investment, Arbitrage) on EVM-compatible L2 chains, driving key project functionalities and scalability.",
    KK_JOB_DESC: "Led the development and maintenance of key projects, resolving over 50% of main project requirements, driving successful project outcomes.",
    GOOD_IDEA_JOB_DESC: "Developed and launched an app for painters and artists to reserve spaces and access news at Taiwan Comic Base, now available on the Google Play Store.",
    PELITH_TIME: "2023-2024",
    KK_TIME: "2021-2023",
    GOOD_IDEA_TIME: "2020-2021",
    PELITH_TW: "Pelith, Taiwan",
    KKCOMPANY_TW: "KKCompany, Taiwan",
    GOODIDEA_TW: "GoodIdea Studio, Taiwan",
    BTC_SENTIMENT_ANALYSIS: "Reddit: BTC Sentiment Analysis",
    BTC_SENTIMENT_ANALYSIS_REPO_URL: "https://medium.com/@eeha8834/analyzing-bitcoin-sentiment-on-reddit-insights-from-user-discussions-13de70192f7b",
    DATA_ANALYSIS: "#Data Analysis",
    DUAL_INVESTMENT: "Dual Investment: A Classic Financial Product in Web3",
    DUAL_INVESTMENT_REPO_URL: "https://dual-investment-git-master-leon-wangs-projects.vercel.app/",
    FULL_STACK_PROJECT: "#Full Stack Project",
    SHARE_PRAWN: "Share Prawn: A Profit-Sharing ERC20 Token",
    SHARE_PRAWN_REPO_URL: "https://github.com/WangWang0226/Share-Prawn",
    BLOCKCHAIN_SMART_CONTRACT: "#Blockchain Smart Contract",
    HACK_VULNERABLE_DEFI: "Damn Vulnerable DeFi Practice",
    HACK_VULNERABLE_DEFI_REPO_URL: "https://github.com/WangWang0226/Hack-Vulnerable-DeFi-Practice",
    BLOCKCHAIN_SECURITY: "#Blockchain Security",
    SQRT_LIQUIDITY_ICO: "SQRT Liquidity ICO",
    SQRT_LIQUIDITY_ICO_REPO_URL: "https://github.com/WangWang0226/SqrtLiquidityICO",
    TOKEN_AIRDROP: "ERC20 Token Airdrop",
    TOKEN_AIRDROP_REPO_URL: "https://github.com/WangWang0226/merkle_pf_airdrop/tree/master", 
    MOTTO: "“Anything worth doing is difficult.”",
    SERVICES: "Services",
    PORTFOLIO: "Portfolio",
    MY_RECENT_WORK: "Demo of My Recent Work"
};