import localFont from "next/font/local";
import "./globals.css";
import { Comic_Neue } from 'next/font/google';

const comicNeue = Comic_Neue({
  weight: ['400','700'], 
  subsets: ['latin'], 
  display: 'swap', 
  style: ['normal', 'italic']
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={comicNeue.className}
      >
        {children}
      </body>
    </html>
  );
}
